/*
 * This file was generated automatically by xsubpp version 1.9508 from the
 * contents of Plugins.xs. Do not edit this file, edit Plugins.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Plugins.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"

#include "const-c.inc"

#include "config.h"
#include "defines.h"

#include "hashlib.h"
#include "utils.h"
#include "configparser.h"
#include "readline.h"
#include "template.h"
#include "clientlib.h"

typedef struct s_cfxs_conn {
  int sock;
  rline_t tsd;
} t_cfxs_conn;


cforum_plg_error(const char *err) {
  SV *errmsg = sv_2mortal(newSVpvf("%s",err));
  SV *errsv  = get_sv("@", TRUE);
  sv_setsv(errsv,errmsg);
}



#line 43 "Plugins.c"

/* INCLUDE:  Including 'const-xs.inc' from 'Plugins.xs' */

XS(XS_CForum__Plugins_constant); /* prototype to pass -Wmissing-prototypes */
XS(XS_CForum__Plugins_constant)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: CForum::Plugins::constant(sv)");
    SP -= items;
    {
#line 4 "const-xs.inc"
#ifdef dXSTARG
	dXSTARG; /* Faster if we have it.  */
#else
	dTARGET;
#endif
	STRLEN		len;
        int		type;
	/* IV		iv;	Uncomment this if you need to return IVs */
	/* NV		nv;	Uncomment this if you need to return NVs */
	/* const char	*pv;	Uncomment this if you need to return PVs */
#line 66 "Plugins.c"
	SV *	sv = ST(0);
	const char *	s = SvPV(sv, len);
#line 18 "const-xs.inc"
	type = constant(aTHX_ s, len);
      /* Return 1 or 2 items. First is error message, or undef if no error.
           Second, if present, is found value */
        switch (type) {
        case PERL_constant_NOTFOUND:
          sv = sv_2mortal(newSVpvf("%s is not a valid CForum::Plugins macro", s));
          PUSHs(sv);
          break;
        case PERL_constant_NOTDEF:
          sv = sv_2mortal(newSVpvf(
	    "Your vendor has not defined CForum::Plugins macro %s, used", s));
          PUSHs(sv);
          break;
	/* Uncomment this if you need to return IVs
        case PERL_constant_ISIV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHi(iv);
          break; */
	/* Uncomment this if you need to return NOs
        case PERL_constant_ISNO:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(&PL_sv_no);
          break; */
	/* Uncomment this if you need to return NVs
        case PERL_constant_ISNV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHn(nv);
          break; */
	/* Uncomment this if you need to return PVs
        case PERL_constant_ISPV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHp(pv, strlen(pv));
          break; */
	/* Uncomment this if you need to return PVNs
        case PERL_constant_ISPVN:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHp(pv, iv);
          break; */
	/* Uncomment this if you need to return SVs
        case PERL_constant_ISSV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(sv);
          break; */
	/* Uncomment this if you need to return UNDEFs
        case PERL_constant_ISUNDEF:
          break; */
	/* Uncomment this if you need to return UVs
        case PERL_constant_ISUV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHu((UV)iv);
          break; */
	/* Uncomment this if you need to return YESs
        case PERL_constant_ISYES:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(&PL_sv_yes);
          break; */
        default:
          sv = sv_2mortal(newSVpvf(
	    "Unexpected return type %d while processing CForum::Plugins macro %s, used",
               type, s));
          PUSHs(sv);
        }
#line 140 "Plugins.c"
	PUTBACK;
	return;
    }
}


/* INCLUDE: Returning to 'Plugins.xs' from 'const-xs.inc' */

XS(XS_CForum__Plugins_get_plugin_group); /* prototype to pass -Wmissing-prototypes */
XS(XS_CForum__Plugins_get_plugin_group)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: CForum::Plugins::get_plugin_group(type)");
    {
	int	type = (int)SvIV(ST(0));
#line 42 "Plugins.xs"
    const u_char *CLASS = "CForum::Plugins::PluginGroup";
#line 159 "Plugins.c"
	t_array *	RETVAL;
#line 44 "Plugins.xs"
    if(type >= MOD_MAX || type <= 0) {
      cforum_plg_error("Not a valid type");
      XSRETURN_UNDEF;
    }

    if(Modules[type].elements == 0) {
      cforum_plg_error("No plugins available for this type");
    }

    RETVAL=&Modules[type];
#line 172 "Plugins.c"
	ST(0) = sv_newmortal();
  sv_setref_pv(ST(0),(char *)CLASS,(void *)RETVAL);

    }
    XSRETURN(1);
}

XS(XS_CForum__Plugins__PluginGroup_new); /* prototype to pass -Wmissing-prototypes */
XS(XS_CForum__Plugins__PluginGroup_new)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: CForum::Plugins::PluginGroup::new(class, type)");
    {
	const u_char *	class = (const u_char *)SvPV_nolen(ST(0));
	int	type = (int)SvIV(ST(1));
#line 65 "Plugins.xs"
    const u_char *CLASS = "CForum::Plugins::PluginGroup";
#line 191 "Plugins.c"
	t_array *	RETVAL;
#line 67 "Plugins.xs"
    if(type >= MOD_MAX || type <= 0) {
      cforum_plg_error("not a valid type");
      XSRETURN_UNDEF;
    }

    if(Modules[type].elements == 0) {
      cforum_plg_error("No plugins available for this type");
      XSRETURN_UNDEF;
    }

    RETVAL=&Modules[type];
#line 205 "Plugins.c"
	ST(0) = sv_newmortal();
  sv_setref_pv(ST(0),(char *)CLASS,(void *)RETVAL);

    }
    XSRETURN(1);
}

XS(XS_CForum__Plugins__PluginGroup_length); /* prototype to pass -Wmissing-prototypes */
XS(XS_CForum__Plugins__PluginGroup_length)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: CForum::Plugins::PluginGroup::length(class)");
    {
	t_array *	class;
	I32	RETVAL;
	dXSTARG;

  if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG)) {
    class = (t_array *)SvIV((SV *)SvRV(ST(0)));
  }
  else {
    class = NULL;
  };
#line 85 "Plugins.xs"
    RETVAL=class->elements;
#line 232 "Plugins.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_CForum__Plugins__PluginGroup_get_plugin); /* prototype to pass -Wmissing-prototypes */
XS(XS_CForum__Plugins__PluginGroup_get_plugin)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: CForum::Plugins::PluginGroup::get_plugin(class, pos)");
    {
	t_array *	class;
	I32	pos = (I32)SvIV(ST(1));
#line 94 "Plugins.xs"
    u_char *CLASS;
    t_handler_config *cfg;
#line 250 "Plugins.c"
	t_handler_config *	RETVAL;

  if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG)) {
    class = (t_array *)SvIV((SV *)SvRV(ST(0)));
  }
  else {
    class = NULL;
  };
#line 97 "Plugins.xs"
    cfg = array_element_at(class,pos);

    switch(cfg->handler) {
      case INIT_HANDLER:
        CLASS = "CForum::Plugins::Plugin::InitHandler";
        break;
      case VIEW_HANDLER:
        CLASS = "CForum::Plugins::Plugin::ViewHandler";
        break;
      case VIEW_INIT_HANDLER:
        CLASS = "CForum::Plugins::Plugin::ViewInitHandler";
        break;
      case VIEW_LIST_HANDLER:
        CLASS = "CForum::Plugins::Plugin::ViewListHandler";
        break;
      case POSTING_HANDLER:
        CLASS = "CForum::Plugins::Plugin::PostingHandler";
        break;
      case CONNECT_INIT_HANDLER:
        CLASS = "CForum::Plugins::Plugin::ConnectInitHandler";
        break;
      case AUTH_HANDLER:
        CLASS = "CForum::Plugins::Plugin::AuthHandler";
        break;
      case ARCHIVE_HANDLER:
        CLASS = "CForum::Plugins::Plugin::ArchiveHandler";
        break;
    }

    RETVAL=cfg;
#line 290 "Plugins.c"
	ST(0) = sv_newmortal();
  sv_setref_pv(ST(0),(char *)CLASS,(void *)RETVAL);

    }
    XSRETURN(1);
}

XS(XS_CForum__Plugins__Plugin__InitHandler_run); /* prototype to pass -Wmissing-prototypes */
XS(XS_CForum__Plugins__Plugin__InitHandler_run)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: CForum::Plugins::Plugin::InitHandler::run(class)");
    {
	t_handler_config *	class;
#line 137 "Plugins.xs"
    t_filter_begin fkt;
#line 308 "Plugins.c"
	int	RETVAL;
	dXSTARG;

  if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG)) {
    class = (t_handler_config *)SvIV((SV *)SvRV(ST(0)));
  }
  else {
    class = NULL;
  };
#line 139 "Plugins.xs"
    if((fkt = (t_filter_begin)class->func) == NULL) {
      XSRETURN_UNDEF;
    }

    RETVAL=fkt(NULL,&fo_default_conf,&fo_view_conf);
#line 324 "Plugins.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_CForum__Plugins__Plugin__ViewHandler_run); /* prototype to pass -Wmissing-prototypes */
XS(XS_CForum__Plugins__Plugin__ViewHandler_run)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: CForum::Plugins::Plugin::ViewHandler::run(class, thread, mode)");
    {
	t_handler_config *	class;
	t_cl_thread *	thread;
	int	mode = (int)SvIV(ST(2));
#line 154 "Plugins.xs"
    t_filter_list fkt;
#line 342 "Plugins.c"
	int	RETVAL;
	dXSTARG;

  if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG)) {
    class = (t_handler_config *)SvIV((SV *)SvRV(ST(0)));
  }
  else {
    class = NULL;
  };

  if(sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG)) {
    thread = (t_cl_thread *)SvIV((SV *)SvRV(ST(1)));
  }
  else {
    thread = NULL;
  };
#line 156 "Plugins.xs"
    if((fkt = (t_filter_list)class->func) == NULL) {
      XSRETURN_UNDEF;
    }

    RETVAL=fkt(NULL,&fo_default_conf,&fo_view_conf,thread,mode);
#line 365 "Plugins.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_CForum__Plugins__Plugin__ViewInitHandler_run); /* prototype to pass -Wmissing-prototypes */
XS(XS_CForum__Plugins__Plugin__ViewInitHandler_run)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: CForum::Plugins::Plugin::ViewInitHandler::run(class, begin, end)");
    {
	t_handler_config *	class;
	t_cf_template *	begin;
	t_cf_template *	end;
#line 171 "Plugins.xs"
    t_filter_init_view fkt;
#line 383 "Plugins.c"
	int	RETVAL;
	dXSTARG;

  if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG)) {
    class = (t_handler_config *)SvIV((SV *)SvRV(ST(0)));
  }
  else {
    class = NULL;
  };

  if(sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG)) {
    begin = (t_cf_template *)SvIV((SV *)SvRV(ST(1)));
  }
  else {
    begin = NULL;
  };

  if(sv_isobject(ST(2)) && (SvTYPE(SvRV(ST(2))) == SVt_PVMG)) {
    end = (t_cf_template *)SvIV((SV *)SvRV(ST(2)));
  }
  else {
    end = NULL;
  };
#line 173 "Plugins.xs"
    if((fkt = (t_filter_init_view)class->func) == NULL) {
      XSRETURN_UNDEF;
    }

    RETVAL=fkt(NULL,&fo_default_conf,&fo_view_conf,begin,end);
#line 413 "Plugins.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_CForum__Plugins__Plugin__ViewListHandler_run); /* prototype to pass -Wmissing-prototypes */
XS(XS_CForum__Plugins__Plugin__ViewListHandler_run)
{
    dXSARGS;
    if (items != 4)
	Perl_croak(aTHX_ "Usage: CForum::Plugins::Plugin::ViewListHandler::run(class, post, ctid, mode)");
    {
	t_handler_config *	class;
	t_message *	post;
	const u_char *	ctid = (const u_char *)SvPV_nolen(ST(2));
	int	mode = (int)SvIV(ST(3));
#line 189 "Plugins.xs"
    t_filter_list_posting fkt;
    u_int64_t tid;
#line 433 "Plugins.c"
	int	RETVAL;
	dXSTARG;

  if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG)) {
    class = (t_handler_config *)SvIV((SV *)SvRV(ST(0)));
  }
  else {
    class = NULL;
  };

  if(sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG)) {
    post = (t_message *)SvIV((SV *)SvRV(ST(1)));
  }
  else {
    post = NULL;
  };
#line 192 "Plugins.xs"
    tid = strtoull(ctid,NULL,10);

    if((fkt = (t_filter_list_posting)class->func) == NULL) {
      XSRETURN_UNDEF;
    }

    RETVAL=fkt(NULL,&fo_default_conf,&fo_view_conf,post,tid,mode);
#line 458 "Plugins.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_CForum__Plugins__Plugin__PostingHandler_run); /* prototype to pass -Wmissing-prototypes */
XS(XS_CForum__Plugins__Plugin__PostingHandler_run)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: CForum::Plugins::Plugin::PostingHandler::run(class, thread, template)");
    {
	t_handler_config *	class;
	t_cl_thread *	thread;
	t_cf_template *	template;
#line 209 "Plugins.xs"
    t_filter_posting fkt;
#line 476 "Plugins.c"
	int	RETVAL;
	dXSTARG;

  if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG)) {
    class = (t_handler_config *)SvIV((SV *)SvRV(ST(0)));
  }
  else {
    class = NULL;
  };

  if(sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG)) {
    thread = (t_cl_thread *)SvIV((SV *)SvRV(ST(1)));
  }
  else {
    thread = NULL;
  };

  if(sv_isobject(ST(2)) && (SvTYPE(SvRV(ST(2))) == SVt_PVMG)) {
    template = (t_cf_template *)SvIV((SV *)SvRV(ST(2)));
  }
  else {
    template = NULL;
  };
#line 211 "Plugins.xs"
    if((fkt = (t_filter_posting)class->func) == NULL) {
      XSRETURN_UNDEF;
    }

    RETVAL=fkt(NULL,&fo_default_conf,&fo_view_conf,thread,template);
#line 506 "Plugins.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_CForum__Plugins__Plugin__ConnectInitHandler_run); /* prototype to pass -Wmissing-prototypes */
XS(XS_CForum__Plugins__Plugin__ConnectInitHandler_run)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: CForum::Plugins::Plugin::ConnectInitHandler::run(class, sock)");
    {
	t_handler_config *	class;
	t_cfxs_conn *	sock;
#line 225 "Plugins.xs"
    t_filter_connect fkt;
#line 523 "Plugins.c"
	int	RETVAL;
	dXSTARG;

  if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG)) {
    class = (t_handler_config *)SvIV((SV *)SvRV(ST(0)));
  }
  else {
    class = NULL;
  };

  if(sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG)) {
    sock = (t_cfxs_conn *)SvIV((SV *)SvRV(ST(1)));
  }
  else {
    sock = NULL;
  };
#line 227 "Plugins.xs"
    if((fkt = (t_filter_connect)class->func) == NULL) {
      XSRETURN_UNDEF;
    }

    RETVAL=fkt(NULL,&fo_default_conf,&fo_view_conf,sock->sock);
#line 546 "Plugins.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_CForum__Plugins__Plugin__AuthHandler_run); /* prototype to pass -Wmissing-prototypes */
XS(XS_CForum__Plugins__Plugin__AuthHandler_run)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: CForum::Plugins::Plugin::AuthHandler::run(class)");
    {
	t_handler_config *	class;
#line 240 "Plugins.xs"
    t_filter_begin fkt;
#line 562 "Plugins.c"
	int	RETVAL;
	dXSTARG;

  if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG)) {
    class = (t_handler_config *)SvIV((SV *)SvRV(ST(0)));
  }
  else {
    class = NULL;
  };
#line 242 "Plugins.xs"
    if((fkt = (t_filter_begin)class->func) == NULL) {
      XSRETURN_UNDEF;
    }

    RETVAL=fkt(NULL,&fo_default_conf,&fo_view_conf);
#line 578 "Plugins.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_CForum__Plugins__Plugin__ArchiveHandler_run); /* prototype to pass -Wmissing-prototypes */
XS(XS_CForum__Plugins__Plugin__ArchiveHandler_run)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: CForum::Plugins::Plugin::ArchiveHandler::run(class)");
    {
	t_handler_config *	class;

  if(sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG)) {
    class = (t_handler_config *)SvIV((SV *)SvRV(ST(0)));
  }
  else {
    class = NULL;
  };
#line 255 "Plugins.xs"
    croak("Sorry, cannot run archive handlers due to they're server plugins");
#line 601 "Plugins.c"
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_CForum__Plugins); /* prototype to pass -Wmissing-prototypes */
XS(boot_CForum__Plugins)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXS("CForum::Plugins::constant", XS_CForum__Plugins_constant, file);
        newXS("CForum::Plugins::get_plugin_group", XS_CForum__Plugins_get_plugin_group, file);
        newXS("CForum::Plugins::PluginGroup::new", XS_CForum__Plugins__PluginGroup_new, file);
        newXS("CForum::Plugins::PluginGroup::length", XS_CForum__Plugins__PluginGroup_length, file);
        newXS("CForum::Plugins::PluginGroup::get_plugin", XS_CForum__Plugins__PluginGroup_get_plugin, file);
        newXS("CForum::Plugins::Plugin::InitHandler::run", XS_CForum__Plugins__Plugin__InitHandler_run, file);
        newXS("CForum::Plugins::Plugin::ViewHandler::run", XS_CForum__Plugins__Plugin__ViewHandler_run, file);
        newXS("CForum::Plugins::Plugin::ViewInitHandler::run", XS_CForum__Plugins__Plugin__ViewInitHandler_run, file);
        newXS("CForum::Plugins::Plugin::ViewListHandler::run", XS_CForum__Plugins__Plugin__ViewListHandler_run, file);
        newXS("CForum::Plugins::Plugin::PostingHandler::run", XS_CForum__Plugins__Plugin__PostingHandler_run, file);
        newXS("CForum::Plugins::Plugin::ConnectInitHandler::run", XS_CForum__Plugins__Plugin__ConnectInitHandler_run, file);
        newXS("CForum::Plugins::Plugin::AuthHandler::run", XS_CForum__Plugins__Plugin__AuthHandler_run, file);
        newXS("CForum::Plugins::Plugin::ArchiveHandler::run", XS_CForum__Plugins__Plugin__ArchiveHandler_run, file);
    XSRETURN_YES;
}

