FIND_PROGRAM (ICU_CONFIG_EXECUTABLE icu-config)

SET (ICU_FOUND FALSE)

IF (ICU_CONFIG_EXECUTABLE)
  EXEC_PROGRAM ("${ICU_CONFIG_EXECUTABLE} --ldflags-libsonly"
    OUTPUT_VARIABLE ICU_LIBRARY
    RETURN_VALUE ERROR_CODE
  )
  SEPARATE_ARGUMENTS(ICU_LIBRARY)

  EXEC_PROGRAM ("${ICU_CONFIG_EXECUTABLE} --cppflags-searchpath|sed s/^-I//"
    OUTPUT_VARIABLE ICU_INCLUDE
    RETURN_VALUE ERROR_CODE
  )
  SEPARATE_ARGUMENTS(ICU_INCLUDE)

  IF (ICU_LIBRARY)
    SET (ICU_FOUND TRUE)
  ENDIF (ICU_LIBRARY)
ENDIF (ICU_CONFIG_EXECUTABLE)


IF (ICU_FIND_REQUIRED)
  IF (NOT ICU_CONFIG_EXECUTABLE)
    MESSAGE (FATAL_ERROR "Could not find icu-config executable")
  ENDIF(NOT ICU_CONFIG_EXECUTABLE)

  IF (NOT ICU_LIBRARY)
    MESSAGE (FATAL_ERROR "Could not find ICU library")
  ENDIF(NOT ICU_LIBRARY)
ENDIF (ICU_FIND_REQUIRED)

