/**
 * \file unicode_properties.c
 * \author Christian Kruse, <cjk@wwwtech.de>
 * \brief Get property of unicode characters
 *
 * This file contains a function to get the property for unicode
 * characters as described in
 * <http://www.unicode.org/Public/UNIDATA/PropList.txt>
 */

/* {{{ Includes */
#include "config.h"
#include "defines.h"

#include <errno.h>
#include <stdlib.h>
#include <stdio.h>
#include <iconv.h>
#include <string.h>

#include <sys/types.h>

#include "charconvert.h"

#include "utils.h"
/* }}} */

int cf_char_property(u_int32_t c) {
  if(c >= 0x9 && c <= 0xD) return CF_UNI_PROP_WHITE_SPACE;
  if(c == 0x20) return CF_UNI_PROP_WHITE_SPACE;
  if(c == 0x85) return CF_UNI_PROP_WHITE_SPACE;
  if(c == 0xA0) return CF_UNI_PROP_WHITE_SPACE;
  if(c == 0x1680) return CF_UNI_PROP_WHITE_SPACE;
  if(c == 0x180E) return CF_UNI_PROP_WHITE_SPACE;
  if(c >= 0x2000 && c <= 0x200A) return CF_UNI_PROP_WHITE_SPACE;
  if(c == 0x2028) return CF_UNI_PROP_WHITE_SPACE;
  if(c == 0x2029) return CF_UNI_PROP_WHITE_SPACE;
  if(c == 0x202F) return CF_UNI_PROP_WHITE_SPACE;
  if(c == 0x205F) return CF_UNI_PROP_WHITE_SPACE;
  if(c == 0x3000) return CF_UNI_PROP_WHITE_SPACE;
  if(c >= 0x200E && c <= 0x200F) return CF_UNI_PROP_BIDI_CONTROL;
  if(c >= 0x202A && c <= 0x202E) return CF_UNI_PROP_BIDI_CONTROL;
  if(c >= 0x200C && c <= 0x200D) return CF_UNI_PROP_JOIN_CONTROL;
  if(c == 0x2D) return CF_UNI_PROP_DASH;
  if(c == 0x58A) return CF_UNI_PROP_DASH;
  if(c == 0x5BE) return CF_UNI_PROP_DASH;
  if(c == 0x1806) return CF_UNI_PROP_DASH;
  if(c >= 0x2010 && c <= 0x2015) return CF_UNI_PROP_DASH;
  if(c == 0x2053) return CF_UNI_PROP_DASH;
  if(c == 0x207B) return CF_UNI_PROP_DASH;
  if(c == 0x208B) return CF_UNI_PROP_DASH;
  if(c == 0x2212) return CF_UNI_PROP_DASH;
  if(c == 0x2E17) return CF_UNI_PROP_DASH;
  if(c == 0x2E1A) return CF_UNI_PROP_DASH;
  if(c == 0x301C) return CF_UNI_PROP_DASH;
  if(c == 0x3030) return CF_UNI_PROP_DASH;
  if(c == 0x30A0) return CF_UNI_PROP_DASH;
  if(c >= 0xFE31 && c <= 0xFE32) return CF_UNI_PROP_DASH;
  if(c == 0xFE58) return CF_UNI_PROP_DASH;
  if(c == 0xFE63) return CF_UNI_PROP_DASH;
  if(c == 0xFF0D) return CF_UNI_PROP_DASH;
  if(c == 0x2D) return CF_UNI_PROP_HYPHEN;
  if(c == 0xAD) return CF_UNI_PROP_HYPHEN;
  if(c == 0x58A) return CF_UNI_PROP_HYPHEN;
  if(c == 0x1806) return CF_UNI_PROP_HYPHEN;
  if(c >= 0x2010 && c <= 0x2011) return CF_UNI_PROP_HYPHEN;
  if(c == 0x2E17) return CF_UNI_PROP_HYPHEN;
  if(c == 0x30FB) return CF_UNI_PROP_HYPHEN;
  if(c == 0xFE63) return CF_UNI_PROP_HYPHEN;
  if(c == 0xFF0D) return CF_UNI_PROP_HYPHEN;
  if(c == 0xFF65) return CF_UNI_PROP_HYPHEN;
  if(c == 0x22) return CF_UNI_PROP_QUOTATION_MARK;
  if(c == 0x27) return CF_UNI_PROP_QUOTATION_MARK;
  if(c == 0xAB) return CF_UNI_PROP_QUOTATION_MARK;
  if(c == 0xBB) return CF_UNI_PROP_QUOTATION_MARK;
  if(c == 0x2018) return CF_UNI_PROP_QUOTATION_MARK;
  if(c == 0x2019) return CF_UNI_PROP_QUOTATION_MARK;
  if(c == 0x201A) return CF_UNI_PROP_QUOTATION_MARK;
  if(c >= 0x201B && c <= 0x201C) return CF_UNI_PROP_QUOTATION_MARK;
  if(c == 0x201D) return CF_UNI_PROP_QUOTATION_MARK;
  if(c == 0x201E) return CF_UNI_PROP_QUOTATION_MARK;
  if(c == 0x201F) return CF_UNI_PROP_QUOTATION_MARK;
  if(c == 0x2039) return CF_UNI_PROP_QUOTATION_MARK;
  if(c == 0x203A) return CF_UNI_PROP_QUOTATION_MARK;
  if(c == 0x300C) return CF_UNI_PROP_QUOTATION_MARK;
  if(c == 0x300D) return CF_UNI_PROP_QUOTATION_MARK;
  if(c == 0x300E) return CF_UNI_PROP_QUOTATION_MARK;
  if(c == 0x300F) return CF_UNI_PROP_QUOTATION_MARK;
  if(c == 0x301D) return CF_UNI_PROP_QUOTATION_MARK;
  if(c >= 0x301E && c <= 0x301F) return CF_UNI_PROP_QUOTATION_MARK;
  if(c == 0xFE41) return CF_UNI_PROP_QUOTATION_MARK;
  if(c == 0xFE42) return CF_UNI_PROP_QUOTATION_MARK;
  if(c == 0xFE43) return CF_UNI_PROP_QUOTATION_MARK;
  if(c == 0xFE44) return CF_UNI_PROP_QUOTATION_MARK;
  if(c == 0xFF02) return CF_UNI_PROP_QUOTATION_MARK;
  if(c == 0xFF07) return CF_UNI_PROP_QUOTATION_MARK;
  if(c == 0xFF62) return CF_UNI_PROP_QUOTATION_MARK;
  if(c == 0xFF63) return CF_UNI_PROP_QUOTATION_MARK;
  if(c == 0x21) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c == 0x2C) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c == 0x2E) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c >= 0x3A && c <= 0x3B) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c == 0x3F) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c == 0x37E) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c == 0x387) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c == 0x589) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c == 0x5C3) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c == 0x60C) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c == 0x61B) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c == 0x61F) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c == 0x6D4) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c >= 0x700 && c <= 0x70A) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c == 0x70C) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c >= 0x7F8 && c <= 0x7F9) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c >= 0x964 && c <= 0x965) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c >= 0xE5A && c <= 0xE5B) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c == 0xF08) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c >= 0xF0D && c <= 0xF12) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c >= 0x104A && c <= 0x104B) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c >= 0x1361 && c <= 0x1368) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c >= 0x166D && c <= 0x166E) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c >= 0x16EB && c <= 0x16ED) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c >= 0x17D4 && c <= 0x17D6) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c == 0x17DA) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c >= 0x1802 && c <= 0x1805) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c >= 0x1808 && c <= 0x1809) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c >= 0x1944 && c <= 0x1945) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c >= 0x1B5A && c <= 0x1B5B) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c >= 0x1B5D && c <= 0x1B5F) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c >= 0x1C3B && c <= 0x1C3F) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c >= 0x1C7E && c <= 0x1C7F) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c >= 0x203C && c <= 0x203D) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c >= 0x2047 && c <= 0x2049) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c == 0x2E2E) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c >= 0x3001 && c <= 0x3002) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c >= 0xA60D && c <= 0xA60F) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c >= 0xA876 && c <= 0xA877) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c >= 0xA8CE && c <= 0xA8CF) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c == 0xA92F) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c >= 0xAA5D && c <= 0xAA5F) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c >= 0xFE50 && c <= 0xFE52) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c >= 0xFE54 && c <= 0xFE57) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c == 0xFF01) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c == 0xFF0C) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c == 0xFF0E) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c >= 0xFF1A && c <= 0xFF1B) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c == 0xFF1F) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c == 0xFF61) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c == 0xFF64) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c == 0x1039F) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c == 0x103D0) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c == 0x1091F) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c >= 0x12470 && c <= 0x12473) return CF_UNI_PROP_TERMINAL_PUNCTUATION;
  if(c == 0x5E) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x3D0 && c <= 0x3D2) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x3D5) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x3F0 && c <= 0x3F1) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x3F4 && c <= 0x3F5) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x2016) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x2032 && c <= 0x2034) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x2040) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x2061 && c <= 0x2064) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x207D) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x207E) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x208D) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x208E) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x20D0 && c <= 0x20DC) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x20E1) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x20E5 && c <= 0x20E6) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x20EB && c <= 0x20EF) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x2102) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x210A && c <= 0x2113) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x2115) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x2119 && c <= 0x211D) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x2124) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x2128) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x2129) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x212C && c <= 0x212D) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x212F && c <= 0x2131) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x2133 && c <= 0x2134) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x2135 && c <= 0x2138) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x213C && c <= 0x213F) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x2145 && c <= 0x2149) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x2195 && c <= 0x2199) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x219C && c <= 0x219F) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x21A1 && c <= 0x21A2) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x21A4 && c <= 0x21A5) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x21A7) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x21A9 && c <= 0x21AD) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x21B0 && c <= 0x21B1) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x21B6 && c <= 0x21B7) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x21BC && c <= 0x21CD) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x21D0 && c <= 0x21D1) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x21D3) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x21D5 && c <= 0x21DB) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x21DD) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x21E4 && c <= 0x21E5) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x23B4 && c <= 0x23B5) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x23B7) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x23D0) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x23E2) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x25A0 && c <= 0x25A1) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x25AE && c <= 0x25B6) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x25BC && c <= 0x25C0) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x25C6 && c <= 0x25C7) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x25CA && c <= 0x25CB) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x25CF && c <= 0x25D3) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x25E2) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x25E4) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x25E7 && c <= 0x25EC) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x2605 && c <= 0x2606) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x2640) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x2642) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x2660 && c <= 0x2663) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x266D && c <= 0x266E) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x27C5) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x27C6) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x27E6) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x27E7) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x27E8) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x27E9) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x27EA) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x27EB) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x27EC) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x27ED) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x27EE) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x27EF) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x2983) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x2984) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x2985) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x2986) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x2987) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x2988) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x2989) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x298A) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x298B) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x298C) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x298D) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x298E) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x298F) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x2990) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x2991) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x2992) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x2993) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x2994) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x2995) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x2996) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x2997) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x2998) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x29D8) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x29D9) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x29DA) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x29DB) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x29FC) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x29FD) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0xFE61) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0xFE63) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0xFE68) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0xFF3C) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0xFF3E) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x1D400 && c <= 0x1D454) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x1D456 && c <= 0x1D49C) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x1D49E && c <= 0x1D49F) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x1D4A2) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x1D4A5 && c <= 0x1D4A6) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x1D4A9 && c <= 0x1D4AC) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x1D4AE && c <= 0x1D4B9) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x1D4BB) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x1D4BD && c <= 0x1D4C3) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x1D4C5 && c <= 0x1D505) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x1D507 && c <= 0x1D50A) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x1D50D && c <= 0x1D514) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x1D516 && c <= 0x1D51C) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x1D51E && c <= 0x1D539) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x1D53B && c <= 0x1D53E) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x1D540 && c <= 0x1D544) return CF_UNI_PROP_OTHER_MATH;
  if(c == 0x1D546) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x1D54A && c <= 0x1D550) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x1D552 && c <= 0x1D6A5) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x1D6A8 && c <= 0x1D6C0) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x1D6C2 && c <= 0x1D6DA) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x1D6DC && c <= 0x1D6FA) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x1D6FC && c <= 0x1D714) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x1D716 && c <= 0x1D734) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x1D736 && c <= 0x1D74E) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x1D750 && c <= 0x1D76E) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x1D770 && c <= 0x1D788) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x1D78A && c <= 0x1D7A8) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x1D7AA && c <= 0x1D7C2) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x1D7C4 && c <= 0x1D7CB) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x1D7CE && c <= 0x1D7FF) return CF_UNI_PROP_OTHER_MATH;
  if(c >= 0x30 && c <= 0x39) return CF_UNI_PROP_HEX_DIGIT;
  if(c >= 0x41 && c <= 0x46) return CF_UNI_PROP_HEX_DIGIT;
  if(c >= 0x61 && c <= 0x66) return CF_UNI_PROP_HEX_DIGIT;
  if(c >= 0xFF10 && c <= 0xFF19) return CF_UNI_PROP_HEX_DIGIT;
  if(c >= 0xFF21 && c <= 0xFF26) return CF_UNI_PROP_HEX_DIGIT;
  if(c >= 0xFF41 && c <= 0xFF46) return CF_UNI_PROP_HEX_DIGIT;
  if(c >= 0x30 && c <= 0x39) return CF_UNI_PROP_ASCII_HEX_DIGIT;
  if(c >= 0x41 && c <= 0x46) return CF_UNI_PROP_ASCII_HEX_DIGIT;
  if(c >= 0x61 && c <= 0x66) return CF_UNI_PROP_ASCII_HEX_DIGIT;
  if(c == 0x345) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x5B0 && c <= 0x5BD) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0x5BF) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x5C1 && c <= 0x5C2) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x5C4 && c <= 0x5C5) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0x5C7) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x610 && c <= 0x61A) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x64B && c <= 0x657) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x659 && c <= 0x65E) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0x670) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x6D6 && c <= 0x6DC) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x6E1 && c <= 0x6E4) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x6E7 && c <= 0x6E8) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0x6ED) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0x711) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x730 && c <= 0x73F) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x7A6 && c <= 0x7B0) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x901 && c <= 0x902) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0x903) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x93E && c <= 0x940) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x941 && c <= 0x948) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x949 && c <= 0x94C) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x962 && c <= 0x963) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0x981) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x982 && c <= 0x983) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x9BE && c <= 0x9C0) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x9C1 && c <= 0x9C4) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x9C7 && c <= 0x9C8) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x9CB && c <= 0x9CC) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0x9D7) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x9E2 && c <= 0x9E3) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xA01 && c <= 0xA02) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0xA03) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xA3E && c <= 0xA40) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xA41 && c <= 0xA42) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xA47 && c <= 0xA48) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xA4B && c <= 0xA4C) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0xA51) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xA70 && c <= 0xA71) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0xA75) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xA81 && c <= 0xA82) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0xA83) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xABE && c <= 0xAC0) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xAC1 && c <= 0xAC5) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xAC7 && c <= 0xAC8) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0xAC9) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xACB && c <= 0xACC) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xAE2 && c <= 0xAE3) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0xB01) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xB02 && c <= 0xB03) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0xB3E) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0xB3F) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0xB40) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xB41 && c <= 0xB44) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xB47 && c <= 0xB48) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xB4B && c <= 0xB4C) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0xB56) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0xB57) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xB62 && c <= 0xB63) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0xB82) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xBBE && c <= 0xBBF) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0xBC0) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xBC1 && c <= 0xBC2) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xBC6 && c <= 0xBC8) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xBCA && c <= 0xBCC) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0xBD7) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xC01 && c <= 0xC03) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xC3E && c <= 0xC40) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xC41 && c <= 0xC44) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xC46 && c <= 0xC48) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xC4A && c <= 0xC4C) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xC55 && c <= 0xC56) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xC62 && c <= 0xC63) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xC82 && c <= 0xC83) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0xCBE) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0xCBF) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xCC0 && c <= 0xCC4) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0xCC6) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xCC7 && c <= 0xCC8) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xCCA && c <= 0xCCB) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0xCCC) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xCD5 && c <= 0xCD6) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xCE2 && c <= 0xCE3) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xD02 && c <= 0xD03) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xD3E && c <= 0xD40) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xD41 && c <= 0xD44) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xD46 && c <= 0xD48) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xD4A && c <= 0xD4C) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0xD57) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xD62 && c <= 0xD63) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xD82 && c <= 0xD83) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xDCF && c <= 0xDD1) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xDD2 && c <= 0xDD4) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0xDD6) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xDD8 && c <= 0xDDF) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xDF2 && c <= 0xDF3) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0xE31) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xE34 && c <= 0xE3A) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0xE4D) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0xEB1) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xEB4 && c <= 0xEB9) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xEBB && c <= 0xEBC) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0xECD) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xF71 && c <= 0xF7E) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0xF7F) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xF80 && c <= 0xF81) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xF90 && c <= 0xF97) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xF99 && c <= 0xFBC) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x102B && c <= 0x102C) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x102D && c <= 0x1030) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0x1031) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x1032 && c <= 0x1036) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0x1038) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x103B && c <= 0x103C) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x103D && c <= 0x103E) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x1056 && c <= 0x1057) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x1058 && c <= 0x1059) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x105E && c <= 0x1060) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0x1062) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x1067 && c <= 0x1068) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x1071 && c <= 0x1074) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0x1082) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x1083 && c <= 0x1084) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x1085 && c <= 0x1086) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0x135F) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x1712 && c <= 0x1713) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x1732 && c <= 0x1733) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x1752 && c <= 0x1753) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x1772 && c <= 0x1773) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0x17B6) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x17B7 && c <= 0x17BD) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x17BE && c <= 0x17C5) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0x17C6) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x17C7 && c <= 0x17C8) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0x18A9) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x1920 && c <= 0x1922) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x1923 && c <= 0x1926) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x1927 && c <= 0x1928) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x1929 && c <= 0x192B) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x1930 && c <= 0x1931) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0x1932) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x1933 && c <= 0x1938) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x19B0 && c <= 0x19C0) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x19C8 && c <= 0x19C9) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x1A17 && c <= 0x1A18) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x1A19 && c <= 0x1A1B) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x1B00 && c <= 0x1B03) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0x1B04) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0x1B35) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x1B36 && c <= 0x1B3A) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0x1B3B) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0x1B3C) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x1B3D && c <= 0x1B41) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0x1B42) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0x1B43) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x1B80 && c <= 0x1B81) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0x1B82) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0x1BA1) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x1BA2 && c <= 0x1BA5) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x1BA6 && c <= 0x1BA7) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x1BA8 && c <= 0x1BA9) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x1C24 && c <= 0x1C2B) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x1C2C && c <= 0x1C33) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x1C34 && c <= 0x1C35) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x24B6 && c <= 0x24E9) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x2DE0 && c <= 0x2DFF) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xA823 && c <= 0xA824) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xA825 && c <= 0xA826) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0xA827) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xA880 && c <= 0xA881) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xA8B4 && c <= 0xA8C3) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xA926 && c <= 0xA92A) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xA947 && c <= 0xA951) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0xA952) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xAA29 && c <= 0xAA2E) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xAA2F && c <= 0xAA30) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xAA31 && c <= 0xAA32) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xAA33 && c <= 0xAA34) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0xAA35 && c <= 0xAA36) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0xAA43) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0xAA4C) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0xAA4D) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0xFB1E) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x10A01 && c <= 0x10A03) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x10A05 && c <= 0x10A06) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c >= 0x10A0C && c <= 0x10A0F) return CF_UNI_PROP_OTHER_ALPHABETIC;
  if(c == 0x3006) return CF_UNI_PROP_IDEOGRAPHIC;
  if(c == 0x3007) return CF_UNI_PROP_IDEOGRAPHIC;
  if(c >= 0x3021 && c <= 0x3029) return CF_UNI_PROP_IDEOGRAPHIC;
  if(c >= 0x3038 && c <= 0x303A) return CF_UNI_PROP_IDEOGRAPHIC;
  if(c >= 0x3400 && c <= 0x4DB5) return CF_UNI_PROP_IDEOGRAPHIC;
  if(c >= 0x4E00 && c <= 0x9FC3) return CF_UNI_PROP_IDEOGRAPHIC;
  if(c >= 0xF900 && c <= 0xFA2D) return CF_UNI_PROP_IDEOGRAPHIC;
  if(c >= 0xFA30 && c <= 0xFA6A) return CF_UNI_PROP_IDEOGRAPHIC;
  if(c >= 0xFA70 && c <= 0xFAD9) return CF_UNI_PROP_IDEOGRAPHIC;
  if(c >= 0x20000 && c <= 0x2A6D6) return CF_UNI_PROP_IDEOGRAPHIC;
  if(c >= 0x2F800 && c <= 0x2FA1D) return CF_UNI_PROP_IDEOGRAPHIC;
  if(c == 0x5E) return CF_UNI_PROP_DIACRITIC;
  if(c == 0x60) return CF_UNI_PROP_DIACRITIC;
  if(c == 0xA8) return CF_UNI_PROP_DIACRITIC;
  if(c == 0xAF) return CF_UNI_PROP_DIACRITIC;
  if(c == 0xB4) return CF_UNI_PROP_DIACRITIC;
  if(c == 0xB7) return CF_UNI_PROP_DIACRITIC;
  if(c == 0xB8) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x2B0 && c <= 0x2C1) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x2C2 && c <= 0x2C5) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x2C6 && c <= 0x2D1) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x2D2 && c <= 0x2DF) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x2E0 && c <= 0x2E4) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x2E5 && c <= 0x2EB) return CF_UNI_PROP_DIACRITIC;
  if(c == 0x2EC) return CF_UNI_PROP_DIACRITIC;
  if(c == 0x2ED) return CF_UNI_PROP_DIACRITIC;
  if(c == 0x2EE) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x2EF && c <= 0x2FF) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x300 && c <= 0x34E) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x350 && c <= 0x357) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x35D && c <= 0x362) return CF_UNI_PROP_DIACRITIC;
  if(c == 0x374) return CF_UNI_PROP_DIACRITIC;
  if(c == 0x375) return CF_UNI_PROP_DIACRITIC;
  if(c == 0x37A) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x384 && c <= 0x385) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x483 && c <= 0x487) return CF_UNI_PROP_DIACRITIC;
  if(c == 0x559) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x591 && c <= 0x5A1) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x5A3 && c <= 0x5BD) return CF_UNI_PROP_DIACRITIC;
  if(c == 0x5BF) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x5C1 && c <= 0x5C2) return CF_UNI_PROP_DIACRITIC;
  if(c == 0x5C4) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x64B && c <= 0x652) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x657 && c <= 0x658) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x6DF && c <= 0x6E0) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x6E5 && c <= 0x6E6) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x6EA && c <= 0x6EC) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x730 && c <= 0x74A) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x7A6 && c <= 0x7B0) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x7EB && c <= 0x7F3) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x7F4 && c <= 0x7F5) return CF_UNI_PROP_DIACRITIC;
  if(c == 0x93C) return CF_UNI_PROP_DIACRITIC;
  if(c == 0x94D) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x951 && c <= 0x954) return CF_UNI_PROP_DIACRITIC;
  if(c == 0x971) return CF_UNI_PROP_DIACRITIC;
  if(c == 0x9BC) return CF_UNI_PROP_DIACRITIC;
  if(c == 0x9CD) return CF_UNI_PROP_DIACRITIC;
  if(c == 0xA3C) return CF_UNI_PROP_DIACRITIC;
  if(c == 0xA4D) return CF_UNI_PROP_DIACRITIC;
  if(c == 0xABC) return CF_UNI_PROP_DIACRITIC;
  if(c == 0xACD) return CF_UNI_PROP_DIACRITIC;
  if(c == 0xB3C) return CF_UNI_PROP_DIACRITIC;
  if(c == 0xB4D) return CF_UNI_PROP_DIACRITIC;
  if(c == 0xBCD) return CF_UNI_PROP_DIACRITIC;
  if(c == 0xC4D) return CF_UNI_PROP_DIACRITIC;
  if(c == 0xCBC) return CF_UNI_PROP_DIACRITIC;
  if(c == 0xCCD) return CF_UNI_PROP_DIACRITIC;
  if(c == 0xD4D) return CF_UNI_PROP_DIACRITIC;
  if(c == 0xDCA) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0xE47 && c <= 0xE4C) return CF_UNI_PROP_DIACRITIC;
  if(c == 0xE4E) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0xEC8 && c <= 0xECC) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0xF18 && c <= 0xF19) return CF_UNI_PROP_DIACRITIC;
  if(c == 0xF35) return CF_UNI_PROP_DIACRITIC;
  if(c == 0xF37) return CF_UNI_PROP_DIACRITIC;
  if(c == 0xF39) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0xF3E && c <= 0xF3F) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0xF82 && c <= 0xF84) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0xF86 && c <= 0xF87) return CF_UNI_PROP_DIACRITIC;
  if(c == 0xFC6) return CF_UNI_PROP_DIACRITIC;
  if(c == 0x1037) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x1039 && c <= 0x103A) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x1087 && c <= 0x108C) return CF_UNI_PROP_DIACRITIC;
  if(c == 0x108D) return CF_UNI_PROP_DIACRITIC;
  if(c == 0x108F) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x17C9 && c <= 0x17D3) return CF_UNI_PROP_DIACRITIC;
  if(c == 0x17DD) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x1939 && c <= 0x193B) return CF_UNI_PROP_DIACRITIC;
  if(c == 0x1B34) return CF_UNI_PROP_DIACRITIC;
  if(c == 0x1B44) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x1B6B && c <= 0x1B73) return CF_UNI_PROP_DIACRITIC;
  if(c == 0x1BAA) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x1C36 && c <= 0x1C37) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x1C78 && c <= 0x1C7D) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x1D2C && c <= 0x1D61) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x1D62 && c <= 0x1D6A) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x1DC4 && c <= 0x1DCF) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x1DFE && c <= 0x1DFF) return CF_UNI_PROP_DIACRITIC;
  if(c == 0x1FBD) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x1FBF && c <= 0x1FC1) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x1FCD && c <= 0x1FCF) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x1FDD && c <= 0x1FDF) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x1FED && c <= 0x1FEF) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x1FFD && c <= 0x1FFE) return CF_UNI_PROP_DIACRITIC;
  if(c == 0x2E2F) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x302A && c <= 0x302F) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x3099 && c <= 0x309A) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x309B && c <= 0x309C) return CF_UNI_PROP_DIACRITIC;
  if(c == 0x30FC) return CF_UNI_PROP_DIACRITIC;
  if(c == 0xA66F) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0xA67C && c <= 0xA67D) return CF_UNI_PROP_DIACRITIC;
  if(c == 0xA67F) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0xA717 && c <= 0xA71F) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0xA720 && c <= 0xA721) return CF_UNI_PROP_DIACRITIC;
  if(c == 0xA788) return CF_UNI_PROP_DIACRITIC;
  if(c == 0xA8C4) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0xA92B && c <= 0xA92D) return CF_UNI_PROP_DIACRITIC;
  if(c == 0xA92E) return CF_UNI_PROP_DIACRITIC;
  if(c == 0xA953) return CF_UNI_PROP_DIACRITIC;
  if(c == 0xFB1E) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0xFE20 && c <= 0xFE26) return CF_UNI_PROP_DIACRITIC;
  if(c == 0xFF3E) return CF_UNI_PROP_DIACRITIC;
  if(c == 0xFF40) return CF_UNI_PROP_DIACRITIC;
  if(c == 0xFF70) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0xFF9E && c <= 0xFF9F) return CF_UNI_PROP_DIACRITIC;
  if(c == 0xFFE3) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x1D167 && c <= 0x1D169) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x1D16D && c <= 0x1D172) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x1D17B && c <= 0x1D182) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x1D185 && c <= 0x1D18B) return CF_UNI_PROP_DIACRITIC;
  if(c >= 0x1D1AA && c <= 0x1D1AD) return CF_UNI_PROP_DIACRITIC;
  if(c == 0xB7) return CF_UNI_PROP_EXTENDER;
  if(c >= 0x2D0 && c <= 0x2D1) return CF_UNI_PROP_EXTENDER;
  if(c == 0x640) return CF_UNI_PROP_EXTENDER;
  if(c == 0x7FA) return CF_UNI_PROP_EXTENDER;
  if(c == 0xE46) return CF_UNI_PROP_EXTENDER;
  if(c == 0xEC6) return CF_UNI_PROP_EXTENDER;
  if(c == 0x1843) return CF_UNI_PROP_EXTENDER;
  if(c == 0x1C36) return CF_UNI_PROP_EXTENDER;
  if(c == 0x1C7B) return CF_UNI_PROP_EXTENDER;
  if(c == 0x3005) return CF_UNI_PROP_EXTENDER;
  if(c >= 0x3031 && c <= 0x3035) return CF_UNI_PROP_EXTENDER;
  if(c >= 0x309D && c <= 0x309E) return CF_UNI_PROP_EXTENDER;
  if(c >= 0x30FC && c <= 0x30FE) return CF_UNI_PROP_EXTENDER;
  if(c == 0xA015) return CF_UNI_PROP_EXTENDER;
  if(c == 0xA60C) return CF_UNI_PROP_EXTENDER;
  if(c == 0xFF70) return CF_UNI_PROP_EXTENDER;
  if(c >= 0x2B0 && c <= 0x2B8) return CF_UNI_PROP_OTHER_LOWERCASE;
  if(c >= 0x2C0 && c <= 0x2C1) return CF_UNI_PROP_OTHER_LOWERCASE;
  if(c >= 0x2E0 && c <= 0x2E4) return CF_UNI_PROP_OTHER_LOWERCASE;
  if(c == 0x345) return CF_UNI_PROP_OTHER_LOWERCASE;
  if(c == 0x37A) return CF_UNI_PROP_OTHER_LOWERCASE;
  if(c >= 0x1D2C && c <= 0x1D61) return CF_UNI_PROP_OTHER_LOWERCASE;
  if(c == 0x1D78) return CF_UNI_PROP_OTHER_LOWERCASE;
  if(c >= 0x1D9B && c <= 0x1DBF) return CF_UNI_PROP_OTHER_LOWERCASE;
  if(c >= 0x2090 && c <= 0x2094) return CF_UNI_PROP_OTHER_LOWERCASE;
  if(c >= 0x2170 && c <= 0x217F) return CF_UNI_PROP_OTHER_LOWERCASE;
  if(c >= 0x24D0 && c <= 0x24E9) return CF_UNI_PROP_OTHER_LOWERCASE;
  if(c == 0x2C7D) return CF_UNI_PROP_OTHER_LOWERCASE;
  if(c == 0xA770) return CF_UNI_PROP_OTHER_LOWERCASE;
  if(c >= 0x2160 && c <= 0x216F) return CF_UNI_PROP_OTHER_UPPERCASE;
  if(c >= 0x24B6 && c <= 0x24CF) return CF_UNI_PROP_OTHER_UPPERCASE;
  if(c >= 0xFDD0 && c <= 0xFDEF) return CF_UNI_PROP_NONCHARACTER_CODE_POINT;
  if(c >= 0xFFFE && c <= 0xFFFF) return CF_UNI_PROP_NONCHARACTER_CODE_POINT;
  if(c >= 0x1FFFE && c <= 0x1FFFF) return CF_UNI_PROP_NONCHARACTER_CODE_POINT;
  if(c >= 0x2FFFE && c <= 0x2FFFF) return CF_UNI_PROP_NONCHARACTER_CODE_POINT;
  if(c >= 0x3FFFE && c <= 0x3FFFF) return CF_UNI_PROP_NONCHARACTER_CODE_POINT;
  if(c >= 0x4FFFE && c <= 0x4FFFF) return CF_UNI_PROP_NONCHARACTER_CODE_POINT;
  if(c >= 0x5FFFE && c <= 0x5FFFF) return CF_UNI_PROP_NONCHARACTER_CODE_POINT;
  if(c >= 0x6FFFE && c <= 0x6FFFF) return CF_UNI_PROP_NONCHARACTER_CODE_POINT;
  if(c >= 0x7FFFE && c <= 0x7FFFF) return CF_UNI_PROP_NONCHARACTER_CODE_POINT;
  if(c >= 0x8FFFE && c <= 0x8FFFF) return CF_UNI_PROP_NONCHARACTER_CODE_POINT;
  if(c >= 0x9FFFE && c <= 0x9FFFF) return CF_UNI_PROP_NONCHARACTER_CODE_POINT;
  if(c >= 0xAFFFE && c <= 0xAFFFF) return CF_UNI_PROP_NONCHARACTER_CODE_POINT;
  if(c >= 0xBFFFE && c <= 0xBFFFF) return CF_UNI_PROP_NONCHARACTER_CODE_POINT;
  if(c >= 0xCFFFE && c <= 0xCFFFF) return CF_UNI_PROP_NONCHARACTER_CODE_POINT;
  if(c >= 0xDFFFE && c <= 0xDFFFF) return CF_UNI_PROP_NONCHARACTER_CODE_POINT;
  if(c >= 0xEFFFE && c <= 0xEFFFF) return CF_UNI_PROP_NONCHARACTER_CODE_POINT;
  if(c >= 0xFFFFE && c <= 0xFFFFF) return CF_UNI_PROP_NONCHARACTER_CODE_POINT;
  if(c >= 0x10FFFE && c <= 0x10FFFF) return CF_UNI_PROP_NONCHARACTER_CODE_POINT;
  if(c == 0x9BE) return CF_UNI_PROP_OTHER_GRAPHEME_EXTEND;
  if(c == 0x9D7) return CF_UNI_PROP_OTHER_GRAPHEME_EXTEND;
  if(c == 0xB3E) return CF_UNI_PROP_OTHER_GRAPHEME_EXTEND;
  if(c == 0xB57) return CF_UNI_PROP_OTHER_GRAPHEME_EXTEND;
  if(c == 0xBBE) return CF_UNI_PROP_OTHER_GRAPHEME_EXTEND;
  if(c == 0xBD7) return CF_UNI_PROP_OTHER_GRAPHEME_EXTEND;
  if(c == 0xCC2) return CF_UNI_PROP_OTHER_GRAPHEME_EXTEND;
  if(c >= 0xCD5 && c <= 0xCD6) return CF_UNI_PROP_OTHER_GRAPHEME_EXTEND;
  if(c == 0xD3E) return CF_UNI_PROP_OTHER_GRAPHEME_EXTEND;
  if(c == 0xD57) return CF_UNI_PROP_OTHER_GRAPHEME_EXTEND;
  if(c == 0xDCF) return CF_UNI_PROP_OTHER_GRAPHEME_EXTEND;
  if(c == 0xDDF) return CF_UNI_PROP_OTHER_GRAPHEME_EXTEND;
  if(c >= 0x200C && c <= 0x200D) return CF_UNI_PROP_OTHER_GRAPHEME_EXTEND;
  if(c >= 0xFF9E && c <= 0xFF9F) return CF_UNI_PROP_OTHER_GRAPHEME_EXTEND;
  if(c == 0x1D165) return CF_UNI_PROP_OTHER_GRAPHEME_EXTEND;
  if(c >= 0x1D16E && c <= 0x1D172) return CF_UNI_PROP_OTHER_GRAPHEME_EXTEND;
  if(c >= 0x2FF0 && c <= 0x2FF1) return CF_UNI_PROP_IDS_BINARY_OPERATOR;
  if(c >= 0x2FF4 && c <= 0x2FFB) return CF_UNI_PROP_IDS_BINARY_OPERATOR;
  if(c >= 0x2FF2 && c <= 0x2FF3) return CF_UNI_PROP_IDS_TRINARY_OPERATOR;
  if(c >= 0x2E80 && c <= 0x2E99) return CF_UNI_PROP_RADICAL;
  if(c >= 0x2E9B && c <= 0x2EF3) return CF_UNI_PROP_RADICAL;
  if(c >= 0x2F00 && c <= 0x2FD5) return CF_UNI_PROP_RADICAL;
  if(c >= 0x3400 && c <= 0x4DB5) return CF_UNI_PROP_UNIFIED_IDEOGRAPH;
  if(c >= 0x4E00 && c <= 0x9FC3) return CF_UNI_PROP_UNIFIED_IDEOGRAPH;
  if(c >= 0xFA0E && c <= 0xFA0F) return CF_UNI_PROP_UNIFIED_IDEOGRAPH;
  if(c == 0xFA11) return CF_UNI_PROP_UNIFIED_IDEOGRAPH;
  if(c >= 0xFA13 && c <= 0xFA14) return CF_UNI_PROP_UNIFIED_IDEOGRAPH;
  if(c == 0xFA1F) return CF_UNI_PROP_UNIFIED_IDEOGRAPH;
  if(c == 0xFA21) return CF_UNI_PROP_UNIFIED_IDEOGRAPH;
  if(c >= 0xFA23 && c <= 0xFA24) return CF_UNI_PROP_UNIFIED_IDEOGRAPH;
  if(c >= 0xFA27 && c <= 0xFA29) return CF_UNI_PROP_UNIFIED_IDEOGRAPH;
  if(c >= 0x20000 && c <= 0x2A6D6) return CF_UNI_PROP_UNIFIED_IDEOGRAPH;
  if(c == 0x34F) return CF_UNI_PROP_OTHER_DEFAULT_IGNORABLE_CODE_POINT;
  if(c >= 0x115F && c <= 0x1160) return CF_UNI_PROP_OTHER_DEFAULT_IGNORABLE_CODE_POINT;
  if(c >= 0x2065 && c <= 0x2069) return CF_UNI_PROP_OTHER_DEFAULT_IGNORABLE_CODE_POINT;
  if(c == 0x3164) return CF_UNI_PROP_OTHER_DEFAULT_IGNORABLE_CODE_POINT;
  if(c == 0xFFA0) return CF_UNI_PROP_OTHER_DEFAULT_IGNORABLE_CODE_POINT;
  if(c >= 0xFFF0 && c <= 0xFFF8) return CF_UNI_PROP_OTHER_DEFAULT_IGNORABLE_CODE_POINT;
  if(c == 0xE0000) return CF_UNI_PROP_OTHER_DEFAULT_IGNORABLE_CODE_POINT;
  if(c >= 0xE0002 && c <= 0xE001F) return CF_UNI_PROP_OTHER_DEFAULT_IGNORABLE_CODE_POINT;
  if(c >= 0xE0080 && c <= 0xE00FF) return CF_UNI_PROP_OTHER_DEFAULT_IGNORABLE_CODE_POINT;
  if(c >= 0xE01F0 && c <= 0xE0FFF) return CF_UNI_PROP_OTHER_DEFAULT_IGNORABLE_CODE_POINT;
  if(c >= 0x340 && c <= 0x341) return CF_UNI_PROP_DEPRECATED;
  if(c == 0x17A3) return CF_UNI_PROP_DEPRECATED;
  if(c == 0x17D3) return CF_UNI_PROP_DEPRECATED;
  if(c >= 0x206A && c <= 0x206F) return CF_UNI_PROP_DEPRECATED;
  if(c == 0xE0001) return CF_UNI_PROP_DEPRECATED;
  if(c >= 0xE0020 && c <= 0xE007F) return CF_UNI_PROP_DEPRECATED;
  if(c >= 0x69 && c <= 0x6A) return CF_UNI_PROP_SOFT_DOTTED;
  if(c == 0x12F) return CF_UNI_PROP_SOFT_DOTTED;
  if(c == 0x249) return CF_UNI_PROP_SOFT_DOTTED;
  if(c == 0x268) return CF_UNI_PROP_SOFT_DOTTED;
  if(c == 0x29D) return CF_UNI_PROP_SOFT_DOTTED;
  if(c == 0x2B2) return CF_UNI_PROP_SOFT_DOTTED;
  if(c == 0x3F3) return CF_UNI_PROP_SOFT_DOTTED;
  if(c == 0x456) return CF_UNI_PROP_SOFT_DOTTED;
  if(c == 0x458) return CF_UNI_PROP_SOFT_DOTTED;
  if(c == 0x1D62) return CF_UNI_PROP_SOFT_DOTTED;
  if(c == 0x1D96) return CF_UNI_PROP_SOFT_DOTTED;
  if(c == 0x1DA4) return CF_UNI_PROP_SOFT_DOTTED;
  if(c == 0x1DA8) return CF_UNI_PROP_SOFT_DOTTED;
  if(c == 0x1E2D) return CF_UNI_PROP_SOFT_DOTTED;
  if(c == 0x1ECB) return CF_UNI_PROP_SOFT_DOTTED;
  if(c == 0x2071) return CF_UNI_PROP_SOFT_DOTTED;
  if(c >= 0x2148 && c <= 0x2149) return CF_UNI_PROP_SOFT_DOTTED;
  if(c == 0x2C7C) return CF_UNI_PROP_SOFT_DOTTED;
  if(c >= 0x1D422 && c <= 0x1D423) return CF_UNI_PROP_SOFT_DOTTED;
  if(c >= 0x1D456 && c <= 0x1D457) return CF_UNI_PROP_SOFT_DOTTED;
  if(c >= 0x1D48A && c <= 0x1D48B) return CF_UNI_PROP_SOFT_DOTTED;
  if(c >= 0x1D4BE && c <= 0x1D4BF) return CF_UNI_PROP_SOFT_DOTTED;
  if(c >= 0x1D4F2 && c <= 0x1D4F3) return CF_UNI_PROP_SOFT_DOTTED;
  if(c >= 0x1D526 && c <= 0x1D527) return CF_UNI_PROP_SOFT_DOTTED;
  if(c >= 0x1D55A && c <= 0x1D55B) return CF_UNI_PROP_SOFT_DOTTED;
  if(c >= 0x1D58E && c <= 0x1D58F) return CF_UNI_PROP_SOFT_DOTTED;
  if(c >= 0x1D5C2 && c <= 0x1D5C3) return CF_UNI_PROP_SOFT_DOTTED;
  if(c >= 0x1D5F6 && c <= 0x1D5F7) return CF_UNI_PROP_SOFT_DOTTED;
  if(c >= 0x1D62A && c <= 0x1D62B) return CF_UNI_PROP_SOFT_DOTTED;
  if(c >= 0x1D65E && c <= 0x1D65F) return CF_UNI_PROP_SOFT_DOTTED;
  if(c >= 0x1D692 && c <= 0x1D693) return CF_UNI_PROP_SOFT_DOTTED;
  if(c >= 0xE40 && c <= 0xE44) return CF_UNI_PROP_LOGICAL_ORDER_EXCEPTION;
  if(c >= 0xEC0 && c <= 0xEC4) return CF_UNI_PROP_LOGICAL_ORDER_EXCEPTION;
  if(c == 0x2118) return CF_UNI_PROP_OTHER_ID_START;
  if(c == 0x212E) return CF_UNI_PROP_OTHER_ID_START;
  if(c >= 0x309B && c <= 0x309C) return CF_UNI_PROP_OTHER_ID_START;
  if(c == 0xB7) return CF_UNI_PROP_OTHER_ID_CONTINUE;
  if(c == 0x387) return CF_UNI_PROP_OTHER_ID_CONTINUE;
  if(c >= 0x1369 && c <= 0x1371) return CF_UNI_PROP_OTHER_ID_CONTINUE;
  if(c == 0x21) return CF_UNI_PROP_STERM;
  if(c == 0x2E) return CF_UNI_PROP_STERM;
  if(c == 0x3F) return CF_UNI_PROP_STERM;
  if(c == 0x55C) return CF_UNI_PROP_STERM;
  if(c == 0x55E) return CF_UNI_PROP_STERM;
  if(c == 0x589) return CF_UNI_PROP_STERM;
  if(c == 0x61F) return CF_UNI_PROP_STERM;
  if(c == 0x6D4) return CF_UNI_PROP_STERM;
  if(c >= 0x700 && c <= 0x702) return CF_UNI_PROP_STERM;
  if(c == 0x7F9) return CF_UNI_PROP_STERM;
  if(c >= 0x964 && c <= 0x965) return CF_UNI_PROP_STERM;
  if(c >= 0x104A && c <= 0x104B) return CF_UNI_PROP_STERM;
  if(c == 0x1362) return CF_UNI_PROP_STERM;
  if(c >= 0x1367 && c <= 0x1368) return CF_UNI_PROP_STERM;
  if(c == 0x166E) return CF_UNI_PROP_STERM;
  if(c == 0x1803) return CF_UNI_PROP_STERM;
  if(c == 0x1809) return CF_UNI_PROP_STERM;
  if(c >= 0x1944 && c <= 0x1945) return CF_UNI_PROP_STERM;
  if(c >= 0x1B5A && c <= 0x1B5B) return CF_UNI_PROP_STERM;
  if(c >= 0x1B5E && c <= 0x1B5F) return CF_UNI_PROP_STERM;
  if(c >= 0x1C3B && c <= 0x1C3C) return CF_UNI_PROP_STERM;
  if(c >= 0x1C7E && c <= 0x1C7F) return CF_UNI_PROP_STERM;
  if(c >= 0x203C && c <= 0x203D) return CF_UNI_PROP_STERM;
  if(c >= 0x2047 && c <= 0x2049) return CF_UNI_PROP_STERM;
  if(c == 0x2E2E) return CF_UNI_PROP_STERM;
  if(c == 0x3002) return CF_UNI_PROP_STERM;
  if(c >= 0xA60E && c <= 0xA60F) return CF_UNI_PROP_STERM;
  if(c >= 0xA876 && c <= 0xA877) return CF_UNI_PROP_STERM;
  if(c >= 0xA8CE && c <= 0xA8CF) return CF_UNI_PROP_STERM;
  if(c == 0xA92F) return CF_UNI_PROP_STERM;
  if(c >= 0xAA5D && c <= 0xAA5F) return CF_UNI_PROP_STERM;
  if(c == 0xFE52) return CF_UNI_PROP_STERM;
  if(c >= 0xFE56 && c <= 0xFE57) return CF_UNI_PROP_STERM;
  if(c == 0xFF01) return CF_UNI_PROP_STERM;
  if(c == 0xFF0E) return CF_UNI_PROP_STERM;
  if(c == 0xFF1F) return CF_UNI_PROP_STERM;
  if(c == 0xFF61) return CF_UNI_PROP_STERM;
  if(c >= 0x180B && c <= 0x180D) return CF_UNI_PROP_VARIATION_SELECTOR;
  if(c >= 0xFE00 && c <= 0xFE0F) return CF_UNI_PROP_VARIATION_SELECTOR;
  if(c >= 0xE0100 && c <= 0xE01EF) return CF_UNI_PROP_VARIATION_SELECTOR;
  if(c >= 0x9 && c <= 0xD) return CF_UNI_PROP_PATTERN_WHITE_SPACE;
  if(c == 0x20) return CF_UNI_PROP_PATTERN_WHITE_SPACE;
  if(c == 0x85) return CF_UNI_PROP_PATTERN_WHITE_SPACE;
  if(c >= 0x200E && c <= 0x200F) return CF_UNI_PROP_PATTERN_WHITE_SPACE;
  if(c == 0x2028) return CF_UNI_PROP_PATTERN_WHITE_SPACE;
  if(c == 0x2029) return CF_UNI_PROP_PATTERN_WHITE_SPACE;
  if(c >= 0x21 && c <= 0x23) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x24) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x25 && c <= 0x27) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x28) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x29) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2A) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2B) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2C) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2D) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2E && c <= 0x2F) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x3A && c <= 0x3B) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x3C && c <= 0x3E) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x3F && c <= 0x40) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x5B) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x5C) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x5D) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x5E) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x60) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x7B) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x7C) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x7D) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x7E) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0xA1) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0xA2 && c <= 0xA5) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0xA6 && c <= 0xA7) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0xA9) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0xAB) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0xAC) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0xAE) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0xB0) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0xB1) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0xB6) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0xBB) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0xBF) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0xD7) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0xF7) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2010 && c <= 0x2015) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2016 && c <= 0x2017) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2018) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2019) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x201A) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x201B && c <= 0x201C) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x201D) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x201E) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x201F) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2020 && c <= 0x2027) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2030 && c <= 0x2038) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2039) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x203A) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x203B && c <= 0x203E) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2041 && c <= 0x2043) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2044) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2045) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2046) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2047 && c <= 0x2051) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2052) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2053) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2055 && c <= 0x205E) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2190 && c <= 0x2194) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2195 && c <= 0x2199) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x219A && c <= 0x219B) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x219C && c <= 0x219F) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x21A0) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x21A1 && c <= 0x21A2) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x21A3) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x21A4 && c <= 0x21A5) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x21A6) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x21A7 && c <= 0x21AD) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x21AE) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x21AF && c <= 0x21CD) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x21CE && c <= 0x21CF) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x21D0 && c <= 0x21D1) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x21D2) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x21D3) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x21D4) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x21D5 && c <= 0x21F3) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x21F4 && c <= 0x22FF) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2300 && c <= 0x2307) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2308 && c <= 0x230B) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x230C && c <= 0x231F) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2320 && c <= 0x2321) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2322 && c <= 0x2328) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2329) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x232A) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x232B && c <= 0x237B) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x237C) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x237D && c <= 0x239A) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x239B && c <= 0x23B3) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x23B4 && c <= 0x23DB) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x23DC && c <= 0x23E1) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x23E2 && c <= 0x23E7) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x23E8 && c <= 0x23FF) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2400 && c <= 0x2426) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2427 && c <= 0x243F) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2440 && c <= 0x244A) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x244B && c <= 0x245F) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2500 && c <= 0x25B6) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x25B7) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x25B8 && c <= 0x25C0) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x25C1) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x25C2 && c <= 0x25F7) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x25F8 && c <= 0x25FF) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2600 && c <= 0x266E) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x266F) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2670 && c <= 0x269D) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x269E && c <= 0x269F) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x26A0 && c <= 0x26BC) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x26BD && c <= 0x26BF) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x26C0 && c <= 0x26C3) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x26C4 && c <= 0x2700) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2701 && c <= 0x2704) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2705) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2706 && c <= 0x2709) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x270A && c <= 0x270B) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x270C && c <= 0x2727) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2728) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2729 && c <= 0x274B) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x274C) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x274D) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x274E) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x274F && c <= 0x2752) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2753 && c <= 0x2755) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2756) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2757) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2758 && c <= 0x275E) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x275F && c <= 0x2760) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2761 && c <= 0x2767) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2768) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2769) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x276A) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x276B) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x276C) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x276D) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x276E) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x276F) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2770) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2771) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2772) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2773) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2774) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2775) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2794) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2795 && c <= 0x2797) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2798 && c <= 0x27AF) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x27B0) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x27B1 && c <= 0x27BE) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x27BF) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x27C0 && c <= 0x27C4) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x27C5) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x27C6) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x27C7 && c <= 0x27CA) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x27CB) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x27CC) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x27CD && c <= 0x27CF) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x27D0 && c <= 0x27E5) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x27E6) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x27E7) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x27E8) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x27E9) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x27EA) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x27EB) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x27EC) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x27ED) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x27EE) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x27EF) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x27F0 && c <= 0x27FF) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2800 && c <= 0x28FF) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2900 && c <= 0x2982) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2983) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2984) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2985) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2986) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2987) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2988) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2989) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x298A) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x298B) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x298C) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x298D) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x298E) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x298F) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2990) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2991) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2992) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2993) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2994) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2995) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2996) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2997) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2998) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2999 && c <= 0x29D7) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x29D8) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x29D9) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x29DA) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x29DB) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x29DC && c <= 0x29FB) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x29FC) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x29FD) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x29FE && c <= 0x2AFF) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2B00 && c <= 0x2B2F) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2B30 && c <= 0x2B44) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2B45 && c <= 0x2B46) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2B47 && c <= 0x2B4C) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2B4D && c <= 0x2B4F) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2B50 && c <= 0x2B54) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2B55 && c <= 0x2BFF) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2E00 && c <= 0x2E01) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2E02) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2E03) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2E04) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2E05) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2E06 && c <= 0x2E08) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2E09) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2E0A) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2E0B) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2E0C) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2E0D) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2E0E && c <= 0x2E16) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2E17) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2E18 && c <= 0x2E19) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2E1A) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2E1B) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2E1C) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2E1D) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2E1E && c <= 0x2E1F) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2E20) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2E21) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2E22) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2E23) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2E24) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2E25) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2E26) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2E27) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2E28) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2E29) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2E2A && c <= 0x2E2E) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2E2F) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x2E30) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x2E31 && c <= 0x2E7F) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x3001 && c <= 0x3003) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x3008) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x3009) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x300A) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x300B) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x300C) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x300D) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x300E) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x300F) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x3010) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x3011) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x3012 && c <= 0x3013) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x3014) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x3015) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x3016) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x3017) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x3018) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x3019) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x301A) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x301B) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x301C) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x301D) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0x301E && c <= 0x301F) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x3020) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0x3030) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0xFD3E) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c == 0xFD3F) return CF_UNI_PROP_PATTERN_SYNTAX;
  if(c >= 0xFE45 && c <= 0xFE46) return CF_UNI_PROP_PATTERN_SYNTAX;
  return -1; /* not known */
}

/* eof */
